flactovk/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from flactovk.views import upload, upload_delete
from frontend.views import ProtectedView, my_logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'flactovk.views.home', name='home'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^accounts/profile/$', ProtectedView.as_view(template_name='profile.html'), name='profile'),
    url(r'^accounts/profile/tracks/$', ProtectedView.as_view(template_name='profile_tracks.html'), name='tracks'),
    url(r'^accounts/logout/$', my_logout, name='logout'),
    # url(r'^flactovk/', include('flactovk.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url( r'upload/', upload, name='jfu_upload' ),
    # You may optionally define a delete url as well
    url( r'^delete/(?P<pk>\d+)$', upload_delete, name='jfu_delete' ),
)

flactovk/flactovk/models.py
from django.db import models
from django.contrib.auth.models import User
import os.path
import hashlib


def _upload_to(instance, filename):
    basename, ext = os.path.splitext(filename)
    return "flac/%s" % hashlib.md5(filename.encode("utf-8")).hexdigest() + ext

class Track(models.Model):
    flac = models.FileField(null=True, upload_to=_upload_to)
    mp3 = models.FileField(null=True, upload_to='mp3')
    user = models.ForeignKey(User)
    uploaded = models.BooleanField(default=False)
    vk_path = models.CharField(max_length=300, null=True)
    vk_hash = models.CharField(max_length=300, null=True)

    def flac_name(self):
        return os.path.basename(self.flac.name)

    def has_mp3(self):
        return bool(self.mp3)

flactovk/frontend/models.py
from django.db import models

# Create your models here.

flactovk/flactovk/forms.py
__author__ = 'moffin'

flactovk/flactovk/views.py
# Create your views here.
from django.views.generic import CreateView
from models import Track
import json
from django.http import HttpResponse
import os
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.decorators.http import require_POST
from jfu.http import upload_receive, UploadResponse, JFUResponse
import os
from django.core.files import File
import subprocess
from social.apps.django_app.default.models import UserSocialAuth
import vkontakte
import requests
import json


class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return HttpResponse(
            self.convert_context_to_json(context),
            content_type='application/json',
            **response_kwargs
        )

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return json.dumps(context)


# class TrackCreateView(CreateView, JSONResponseMixin):
#     model = Track
#     fields = ['mp3']
#
#     def form_valid(self, form):
#         track = form.save(commit=False)
#         track.user = self.request.user
#         track.save()
#
#         context = self.get_context_data()
#         return super(TrackCreateView, self).render_to_response(context)
#
#     def render_to_response(self, context, **response_kwargs):
#         return JSONResponseMixin.render_to_json_response(context)

@require_POST
def upload(request):

    # The assumption here is that jQuery File Upload
    # has been configured to send files one at a time.
    # If multiple files can be uploaded simulatenously,
    # 'file' may be a list of files.

    file = upload_receive(request)

    instance = Track(flac=file, user=request.user)
    instance.save()

    basename = os.path.basename(instance.flac.file.name)
    filename = "%s%s%s" % (settings.MEDIA_ROOT, 'mp3/', basename)
    mp3_filename = "%s%s" % (filename, '.mp3')

    # os.chdir("%s%s" % (settings.MEDIA_ROOT, 'mp3/'))
    resp = os.system('track2track -V quiet -t mp3 -o "%s" "%s"' % (mp3_filename, instance.flac.path))
    # subprocess.call(['track2track -V quiet -t mp3 -o "%s" "%s"' % (mp3_filename, instance.flac.path)])
    instance.mp3 = "mp3/%s" % os.path.basename(mp3_filename)

    # f = open(filename, 'r')
    # djangofile = File(f)
    # instance.mp3.save('filename.txt', djangofile)
    # f.close()

    instance.save()

    us = UserSocialAuth.objects.get(user=request.user)
    token = us.extra_data.get("access_token")
    vk = vkontakte.API(token=token)
    server = vk.audio.getUploadServer()
    url = server.get("upload_url")
    files = {'file' : open(instance.mp3.path, 'rb')}
    r = requests.post(url, files=files)
    _json = json.loads(r.text)
    vk.audio.save(server=_json.get('server'), hash=_json.get('hash'), audio=_json.get('audio'))

    file_dict = {
        'name': basename,
        'size': instance.flac.file.size,

        # The assumption is that file_field is a FileField that saves to
        # the 'media' directory.
        'url': settings.MEDIA_URL + 'flac/' + basename,
        'thumbnail_url': settings.MEDIA_URL + 'flac/' + basename,
        'delete_url': reverse('jfu_delete', kwargs={'pk': instance.pk}),
        'delete_type': 'POST',
        'r' : r.text
    }

    return UploadResponse(request, file_dict)

@require_POST
def upload_delete( request, pk ):
    # An example implementation.
    success = True
    try:
        instance = Track.objects.get( pk = pk )
        os.unlink(instance.flac.file.name)
        instance.delete()
    except Track.DoesNotExist:
        success = False

    return JFUResponse( request, success )

flactovk/frontend/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.shortcuts import redirect


class ProtectedView(TemplateView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProtectedView, self).dispatch(*args, **kwargs)


def my_logout(request):
    logout(request)
    return redirect('/')

flactovk/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

    <title>Загружайте flac-треки в сеть vkontakte \0</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/bootstrap/navbar.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="/static/bootstrap/assets/js/html5shiv.js"></script>
      <script src="/static/bootstrap/assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Flacshtok</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="{% url 'profile' %}">личный кабинет</a></li>
              {% if request.user.is_authenticated %}
                  <li><a href="{% url 'logout' %}">выйти</a></li>
              {% endif %}
            <li><a href="../navbar-static-top/">о нас</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        {% block content %}

        {% endblock %}
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
{#    <script src="/static/bootstrap/assets/js/jquery.js"></script>#}
    <script src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <script>
        jQuery(document).ajaxSend(function(event, xhr, settings) {
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            function sameOrigin(url) {
                // url could be relative or scheme relative or absolute
                var host = document.location.host; // host + port
                var protocol = document.location.protocol;
                var sr_origin = '//' + host;
                var origin = protocol + sr_origin;
                // Allow absolute or scheme relative URLs to same origin
                return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                    // or any other URL that isn't scheme relative or absolute i.e relative.
                        !(/^(\/\/|http:|https:).*/.test(url));
            }
            function safeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        });
    </script>
  </body>
</html>

flactovk/frontend/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Flacshtok</h1>
    <p>Заливайте музло вконтакте в формате flac. Чтобы начать загружать музыку в vk, вам надо выполнить вход через
        ваш аккаунт. Мы попросим права на заливку аудиозаписей, которые (права) не будем использовать кроме как для того
        чтобы загружать вами выбранные треки.</p>
    <p>
        <a class="btn btn-lg btn-primary" href="{% url 'profile' %}">Войти с помощью vk &raquo;</a>
    </p>
{% endblock %}

flactovk/frontend/templates/my_uploader.html
{% extends 'jfu/upload_form.html' %}

{% block JS_OPTS %}
    autoUpload: true,
    maxNumberOfFiles: 5,
    sequentialUploads: true,
    acceptFileTypes: /(\.|\/)(flac)$/i
{% endblock %}

{% block JS_BOOTSTRAP %}
{% endblock %}


{% block CSS_BOOTSTRAP %}
    {% comment %}
    This is already included.
    {% endcomment %}
{% endblock %}

{% block UPLOAD_FORM_BUTTON_BAR_CONTROL %}
{% endblock %}

flactovk/frontend/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <ul class="nav nav-pills">
        <li class="active"><a href="#">Загрузка</a></li>
        <li><a href="{% url 'tracks' %}">Мои треки</a></li>
    </ul>
    <h1>Загрузка треков в формате flac</h1>
    {% load jfutags %}
    <div class="padded">
        {% jfu 'my_uploader.html' 'jfu_upload' %}
    </div>
{% endblock %}

flactovk/frontend/templates/profile_tracks.html
{% extends 'base.html' %}

{% block content %}
    <ul class="nav nav-pills">
        <li ><a href="{% url 'profile' %}">Загрузка</a></li>
        <li class="active"><a href="#">Мои треки</a></li>
    </ul>
    <h1>Мои треки</h1>
    <table class="table">
        <thead>
            <tr>
                <td>Файл</td>
            </tr>
        </thead>
        <tbody>
            {% for track in request.user.track_set.all %}
                <tr>
                    <td><a href="{{ track.flac.url }}">{{ track.flac_name }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}